#! /bin/sh

sxhkd &

compton --config compton.conf -b 

bspc monitor -d I II III IV V VI VII VIII IX X

feh --bg-fill "/home/killo/Pictures/82t53bh31uf31.jpg"

bspc config border_width         1
bspc config window_gap          25

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus      true
bspc config history_aware_focus      true
bspc config focus_follows_pointer      true
bspc config center_pseudo_tiled      true

bspc rule -a Gimp desktop='^8' state=floating follow=on

$HOME/.config/polybar/launch.sh
